# Project: Proyecto final
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Main.o alumno.o administradorcontrasena.o User.o admin.o UserMenu.o Carreras.o cursos.o
LINKOBJ  = Main.o alumno.o administradorcontrasena.o User.o admin.o UserMenu.o Carreras.o cursos.o
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "Proyecto final.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Program Files (x86)\Embarcadero\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Main.o: Main.cpp
	$(CPP) -c Main.cpp -o Main.o $(CXXFLAGS)

alumno.o: alumno.cpp
	$(CPP) -c alumno.cpp -o alumno.o $(CXXFLAGS)

administradorcontrasena.o: administradorcontrasena.cpp
	$(CPP) -c administradorcontrasena.cpp -o administradorcontrasena.o $(CXXFLAGS)

User.o: User.cpp
	$(CPP) -c User.cpp -o User.o $(CXXFLAGS)

admin.o: admin.cpp
	$(CPP) -c admin.cpp -o admin.o $(CXXFLAGS)

UserMenu.o: UserMenu.cpp
	$(CPP) -c UserMenu.cpp -o UserMenu.o $(CXXFLAGS)

Carreras.o: Carreras.cpp
	$(CPP) -c Carreras.cpp -o Carreras.o $(CXXFLAGS)

cursos.o: cursos.cpp
	$(CPP) -c cursos.cpp -o cursos.o $(CXXFLAGS)
