# Project: N01 Supertech
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = tablas/Carreras.o tablas/cursos.o Usuarios/admin.o Usuarios/alumno.o Usuarios/UserMenu.o Otros/Main.o tablas/Secciones.o tablas/Catedraticos.o "tablas/Alumno\ tabla.o" "tablas/Catedraticos\ por\ cursos.o" "Usuarios/Menu\ tablas.o" "Usuarios/Catedraticos\ Menu.o" tablas/Evaluacion.o tablas/Usuarios.o tablas/Password.o "tablas/Reportes\ de\ alumnos.o"
LINKOBJ  = tablas/Carreras.o tablas/cursos.o Usuarios/admin.o Usuarios/alumno.o Usuarios/UserMenu.o Otros/Main.o tablas/Secciones.o tablas/Catedraticos.o "tablas/Alumno tabla.o" "tablas/Catedraticos por cursos.o" "Usuarios/Menu tablas.o" "Usuarios/Catedraticos Menu.o" tablas/Evaluacion.o tablas/Usuarios.o tablas/Password.o "tablas/Reportes de alumnos.o"
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "No1 Supetech.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Program Files (x86)\Embarcadero\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

tablas/Carreras.o: tablas/Carreras.cpp
	$(CPP) -c tablas/Carreras.cpp -o tablas/Carreras.o $(CXXFLAGS)

tablas/cursos.o: tablas/cursos.cpp
	$(CPP) -c tablas/cursos.cpp -o tablas/cursos.o $(CXXFLAGS)

Usuarios/admin.o: Usuarios/admin.cpp
	$(CPP) -c Usuarios/admin.cpp -o Usuarios/admin.o $(CXXFLAGS)

Usuarios/alumno.o: Usuarios/alumno.cpp
	$(CPP) -c Usuarios/alumno.cpp -o Usuarios/alumno.o $(CXXFLAGS)

Usuarios/UserMenu.o: Usuarios/UserMenu.cpp
	$(CPP) -c Usuarios/UserMenu.cpp -o Usuarios/UserMenu.o $(CXXFLAGS)

Otros/Main.o: Otros/Main.cpp
	$(CPP) -c Otros/Main.cpp -o Otros/Main.o $(CXXFLAGS)

tablas/Secciones.o: tablas/Secciones.cpp
	$(CPP) -c tablas/Secciones.cpp -o tablas/Secciones.o $(CXXFLAGS)

tablas/Catedraticos.o: tablas/Catedraticos.cpp
	$(CPP) -c tablas/Catedraticos.cpp -o tablas/Catedraticos.o $(CXXFLAGS)

"tablas/Alumno\ tabla.o": tablas/Alumno\ tabla.cpp
	$(CPP) -c "tablas/Alumno tabla.cpp" -o "tablas/Alumno tabla.o" $(CXXFLAGS)

"tablas/Catedraticos\ por\ cursos.o": tablas/Catedraticos\ por\ cursos.cpp
	$(CPP) -c "tablas/Catedraticos por cursos.cpp" -o "tablas/Catedraticos por cursos.o" $(CXXFLAGS)

"Usuarios/Menu\ tablas.o": Usuarios/Menu\ tablas.cpp
	$(CPP) -c "Usuarios/Menu tablas.cpp" -o "Usuarios/Menu tablas.o" $(CXXFLAGS)

"Usuarios/Catedraticos\ Menu.o": Usuarios/Catedraticos\ Menu.cpp
	$(CPP) -c "Usuarios/Catedraticos Menu.cpp" -o "Usuarios/Catedraticos Menu.o" $(CXXFLAGS)

tablas/Evaluacion.o: tablas/Evaluacion.cpp
	$(CPP) -c tablas/Evaluacion.cpp -o tablas/Evaluacion.o $(CXXFLAGS)

tablas/Usuarios.o: tablas/Usuarios.cpp
	$(CPP) -c tablas/Usuarios.cpp -o tablas/Usuarios.o $(CXXFLAGS)

tablas/Password.o: tablas/Password.cpp
	$(CPP) -c tablas/Password.cpp -o tablas/Password.o $(CXXFLAGS)

"tablas/Reportes\ de\ alumnos.o": tablas/Reportes\ de\ alumnos.cpp
	$(CPP) -c "tablas/Reportes de alumnos.cpp" -o "tablas/Reportes de alumnos.o" $(CXXFLAGS)
